services:
  eikona.tessa.controller.apireferencedata:
    class: Eikona\Tessa\ReferenceDataAttributeBundle\Controller\ApiController
    public: true
    arguments:
      - '@doctrine.orm.entity_manager'