services:
    eikona.tessa.listener.tessa_notification:
        class: Eikona\Tessa\ConnectorBundle\EventListener\TessaNotificationListener
        arguments:
            - '@eikona.tessa'
            - '@doctrine.orm.entity_manager'
            - '@pim_catalog.repository.product'
            - '@pim_catalog.repository.product_model'
            - '@eikona.tessa.notification_queue.service'
            - '@pim_user.context.user'
            - '@request_stack'
        tags:
            - { name: kernel.event_listener, event: akeneo.storage.post_save, method: onPostSave }
            - { name: kernel.event_listener, event: akeneo.storage.pre_remove, method: onPreRemove }
            - { name: kernel.event_listener, event: akeneo.storage.post_remove, method: onPostRemove }
